<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

$countries = array();
$countries["DZ"] = array('value' => 213, 'name' => 'Algeria');
$countries["AD"] = array('value' => 376, 'name' => 'Andorra');
$countries["AO"] = array('value' => 244, 'name' => 'Angola');
$countries["AI"] = array('value' => 1264, 'name' => 'Anguilla');
$countries["AG"] = array('value' => 1268, 'name' => 'Antigua & Barbuda');
$countries["AR"] = array('value' => 54, 'name' => 'Argentina');
$countries["AM"] = array('value' => 374, 'name' => 'Armenia');
$countries["AW"] = array('value' => 297, 'name' => 'Aruba');
$countries["AU"] = array('value' => 61, 'name' => 'Australia');
$countries["AT"] = array('value' => 43, 'name' => 'Austria');
$countries["AZ"] = array('value' => 994, 'name' => 'Azerbaijan');
$countries["BS"] = array('value' => 1242, 'name' => 'Bahamas');
$countries["BH"] = array('value' => 973, 'name' => 'Bahrain');
$countries["BD"] = array('value' => 880, 'name' => 'Bangladesh');
$countries["BB"] = array('value' => 1246, 'name' => 'Barbados');
$countries["BY"] = array('value' => 375, 'name' => 'Belarus');
$countries["BE"] = array('value' => 32, 'name' => 'Belgium');
$countries["BZ"] = array('value' => 501, 'name' => 'Belize');
$countries["BJ"] = array('value' => 229, 'name' => 'Benin');
$countries["BM"] = array('value' => 1441, 'name' => 'Bermuda');
$countries["BT"] = array('value' => 975, 'name' => 'Bhutan');
$countries["BO"] = array('value' => 591, 'name' => 'Bolivia');
$countries["BA"] = array('value' => 387, 'name' => 'Bosnia Herzegovina');
$countries["BW"] = array('value' => 267, 'name' => 'Botswana');
$countries["BR"] = array('value' => 55, 'name' => 'Brazil');
$countries["BN"] = array('value' => 673, 'name' => 'Brunei');
$countries["BG"] = array('value' => 359, 'name' => 'Bulgaria');
$countries["BF"] = array('value' => 226, 'name' => 'Burkina Faso');
$countries["BI"] = array('value' => 257, 'name' => 'Burundi');
$countries["KH"] = array('value' => 855, 'name' => 'Cambodia');
$countries["CM"] = array('value' => 237, 'name' => 'Cameroon');
$countries["CA"] = array('value' => 1, 'name' => 'Canada');
$countries["CV"] = array('value' => 238, 'name' => 'Cape Verde Islands');
$countries["KY"] = array('value' => 1345, 'name' => 'Cayman Islands');
$countries["CF"] = array('value' => 236, 'name' => 'Central African Republic');
$countries["CL"] = array('value' => 56, 'name' => 'Chile');
$countries["CN"] = array('value' => 86, 'name' => 'China');
$countries["CO"] = array('value' => 57, 'name' => 'Colombia');
$countries["KM"] = array('value' => 269, 'name' => 'Comoros');
$countries["CG"] = array('value' => 242, 'name' => 'Congo');
$countries["CK"] = array('value' => 682, 'name' => 'Cook Islands');
$countries["CR"] = array('value' => 506, 'name' => 'Costa Rica');
$countries["HR"] = array('value' => 385, 'name' => 'Croatia');
$countries["CU"] = array('value' => 53, 'name' => 'Cuba');
$countries["CY"] = array('value' => 90, 'name' => 'Cyprus - North');
$countries["CY"] = array('value' => 357, 'name' => 'Cyprus - South');
$countries["CZ"] = array('value' => 420, 'name' => 'Czech Republic');
$countries["DK"] = array('value' => 45, 'name' => 'Denmark');
$countries["DJ"] = array('value' => 253, 'name' => 'Djibouti');
$countries["DM"] = array('value' => 1809, 'name' => 'Dominica');
$countries["DO"] = array('value' => 1809, 'name' => 'Dominican Republic');
$countries["EC"] = array('value' => 593, 'name' => 'Ecuador');
$countries["EG"] = array('value' => 20, 'name' => 'Egypt');
$countries["SV"] = array('value' => 503, 'name' => 'El Salvador');
$countries["GQ"] = array('value' => 240, 'name' => 'Equatorial Guinea');
$countries["ER"] = array('value' => 291, 'name' => 'Eritrea');
$countries["EE"] = array('value' => 372, 'name' => 'Estonia');
$countries["ET"] = array('value' => 251, 'name' => 'Ethiopia');
$countries["FK"] = array('value' => 500, 'name' => 'Falkland Islands');
$countries["FO"] = array('value' => 298, 'name' => 'Faroe Islands');
$countries["FJ"] = array('value' => 679, 'name' => 'Fiji');
$countries["FI"] = array('value' => 358, 'name' => 'Finland');
$countries["FR"] = array('value' => 33, 'name' => 'France');
$countries["GF"] = array('value' => 594, 'name' => 'French Guiana');
$countries["PF"] = array('value' => 689, 'name' => 'French Polynesia');
$countries["GA"] = array('value' => 241, 'name' => 'Gabon');
$countries["GM"] = array('value' => 220, 'name' => 'Gambia');
$countries["GE"] = array('value' => 7880, 'name' => 'Georgia');
$countries["DE"] = array('value' => 49, 'name' => 'Germany');
$countries["GH"] = array('value' => 233, 'name' => 'Ghana');
$countries["GI"] = array('value' => 350, 'name' => 'Gibraltar');
$countries["GR"] = array('value' => 30, 'name' => 'Greece');
$countries["GL"] = array('value' => 299, 'name' => 'Greenland');
$countries["GD"] = array('value' => 1473, 'name' => 'Grenada');
$countries["GP"] = array('value' => 590, 'name' => 'Guadeloupe');
$countries["GU"] = array('value' => 671, 'name' => 'Guam');
$countries["GT"] = array('value' => 502, 'name' => 'Guatemala');
$countries["GN"] = array('value' => 224, 'name' => 'Guinea');
$countries["GW"] = array('value' => 245, 'name' => 'Guinea - Bissau');
$countries["GY"] = array('value' => 592, 'name' => 'Guyana');
$countries["HT"] = array('value' => 509, 'name' => 'Haiti');
$countries["HN"] = array('value' => 504, 'name' => 'Honduras');
$countries["HK"] = array('value' => 852, 'name' => 'Hong Kong');
$countries["HU"] = array('value' => 36, 'name' => 'Hungary');
$countries["IS"] = array('value' => 354, 'name' => 'Iceland');
$countries["IN"] = array('value' => 91, 'name' => 'India');
$countries["ID"] = array('value' => 62, 'name' => 'Indonesia');
$countries["IQ"] = array('value' => 964, 'name' => 'Iraq');
$countries["IR"] = array('value' => 98, 'name' => 'Iran');
$countries["IE"] = array('value' => 353, 'name' => 'Ireland');
$countries["IL"] = array('value' => 972, 'name' => 'Israel');
$countries["IT"] = array('value' => 39, 'name' => 'Italy');
$countries["JM"] = array('value' => 1876, 'name' => 'Jamaica');
$countries["JP"] = array('value' => 81, 'name' => 'Japan');
$countries["JO"] = array('value' => 962, 'name' => 'Jordan');
$countries["KZ"] = array('value' => 7, 'name' => 'Kazakhstan');
$countries["KE"] = array('value' => 254, 'name' => 'Kenya');
$countries["KI"] = array('value' => 686, 'name' => 'Kiribati');
$countries["KP"] = array('value' => 850, 'name' => 'Korea - North');
$countries["KR"] = array('value' => 82, 'name' => 'Korea - South');
$countries["KW"] = array('value' => 965, 'name' => 'Kuwait');
$countries["KG"] = array('value' => 996, 'name' => 'Kyrgyzstan');
$countries["LA"] = array('value' => 856, 'name' => 'Laos');
$countries["LV"] = array('value' => 371, 'name' => 'Latvia');
$countries["LB"] = array('value' => 961, 'name' => 'Lebanon');
$countries["LS"] = array('value' => 266, 'name' => 'Lesotho');
$countries["LR"] = array('value' => 231, 'name' => 'Liberia');
$countries["LY"] = array('value' => 218, 'name' => 'Libya');
$countries["LI"] = array('value' => 417, 'name' => 'Liechtenstein');
$countries["LT"] = array('value' => 370, 'name' => 'Lithuania');
$countries["LU"] = array('value' => 352, 'name' => 'Luxembourg');
$countries["MO"] = array('value' => 853, 'name' => 'Macao');
$countries["MK"] = array('value' => 389, 'name' => 'Macedonia');
$countries["MG"] = array('value' => 261, 'name' => 'Madagascar');
$countries["MW"] = array('value' => 265, 'name' => 'Malawi');
$countries["MY"] = array('value' => 60, 'name' => 'Malaysia');
$countries["MV"] = array('value' => 960, 'name' => 'Maldives');
$countries["ML"] = array('value' => 223, 'name' => 'Mali');
$countries["MT"] = array('value' => 356, 'name' => 'Malta');
$countries["MH"] = array('value' => 692, 'name' => 'Marshall Islands');
$countries["MQ"] = array('value' => 596, 'name' => 'Martinique');
$countries["MR"] = array('value' => 222, 'name' => 'Mauritania');
$countries["YT"] = array('value' => 269, 'name' => 'Mayotte');
$countries["MX"] = array('value' => 52, 'name' => 'Mexico');
$countries["FM"] = array('value' => 691, 'name' => 'Micronesia');
$countries["MD"] = array('value' => 373, 'name' => 'Moldova');
$countries["MC"] = array('value' => 377, 'name' => 'Monaco');
$countries["MN"] = array('value' => 976, 'name' => 'Mongolia');
$countries["MS"] = array('value' => 1664, 'name' => 'Montserrat');
$countries["MA"] = array('value' => 212, 'name' => 'Morocco');
$countries["MZ"] = array('value' => 258, 'name' => 'Mozambique');
$countries["MN"] = array('value' => 95, 'name' => 'Myanmar');
$countries["NA"] = array('value' => 264, 'name' => 'Namibia');
$countries["NR"] = array('value' => 674, 'name' => 'Nauru');
$countries["NP"] = array('value' => 977, 'name' => 'Nepal');
$countries["NL"] = array('value' => 31, 'name' => 'Netherlands');
$countries["NC"] = array('value' => 687, 'name' => 'New Caledonia');
$countries["NZ"] = array('value' => 64, 'name' => 'New Zealand');
$countries["NI"] = array('value' => 505, 'name' => 'Nicaragua');
$countries["NE"] = array('value' => 227, 'name' => 'Niger');
$countries["NG"] = array('value' => 234, 'name' => 'Nigeria');
$countries["NU"] = array('value' => 683, 'name' => 'Niue');
$countries["NF"] = array('value' => 672, 'name' => 'Norfolk Islands');
$countries["NP"] = array('value' => 670, 'name' => 'Northern Marianas');
$countries["NO"] = array('value' => 47, 'name' => 'Norway');
$countries["OM"] = array('value' => 968, 'name' => 'Oman');
$countries["PK"] = array('value' => 92, 'name' => 'Pakistan');
$countries["PW"] = array('value' => 680, 'name' => 'Palau');
$countries["PA"] = array('value' => 507, 'name' => 'Panama');
$countries["PG"] = array('value' => 675, 'name' => 'Papua New Guinea');
$countries["PY"] = array('value' => 595, 'name' => 'Paraguay');
$countries["PE"] = array('value' => 51, 'name' => 'Peru');
$countries["PH"] = array('value' => 63, 'name' => 'Philippines');
$countries["PL"] = array('value' => 48, 'name' => 'Poland');
$countries["PT"] = array('value' => 351, 'name' => 'Portugal');
$countries["PR"] = array('value' => 1787, 'name' => 'Puerto Rico');
$countries["QA"] = array('value' => 974, 'name' => 'Qatar');
$countries["RE"] = array('value' => 262, 'name' => 'Reunion');
$countries["RO"] = array('value' => 40, 'name' => 'Romania');
$countries["RU"] = array('value' => 7, 'name' => 'Russia');
$countries["RW"] = array('value' => 250, 'name' => 'Rwanda');
$countries["SM"] = array('value' => 378, 'name' => 'San Marino');
$countries["ST"] = array('value' => 239, 'name' => 'Sao Tome &amp; Principe');
$countries["SA"] = array('value' => 966, 'name' => 'Saudi Arabia');
$countries["SN"] = array('value' => 221, 'name' => 'Senegal');
$countries["CS"] = array('value' => 381, 'name' => 'Serbia');
$countries["SC"] = array('value' => 248, 'name' => 'Seychelles');
$countries["SL"] = array('value' => 232, 'name' => 'Sierra Leone');
$countries["SG"] = array('value' => 65, 'name' => 'Singapore');
$countries["SK"] = array('value' => 421, 'name' => 'Slovak Republic');
$countries["SI"] = array('value' => 386, 'name' => 'Slovenia');
$countries["SB"] = array('value' => 677, 'name' => 'Solomon Islands');
$countries["SO"] = array('value' => 252, 'name' => 'Somalia');
$countries["ZA"] = array('value' => 27, 'name' => 'South Africa');
$countries["ES"] = array('value' => 34, 'name' => 'Spain');
$countries["LK"] = array('value' => 94, 'name' => 'Sri Lanka');
$countries["SH"] = array('value' => 290, 'name' => 'St. Helena');
$countries["KN"] = array('value' => 1869, 'name' => 'St. Kitts');
$countries["SC"] = array('value' => 1758, 'name' => 'St. Lucia');
$countries["SR"] = array('value' => 597, 'name' => 'Suriname');
$countries["SD"] = array('value' => 249, 'name' => 'Sudan');
$countries["SZ"] = array('value' => 268, 'name' => 'Swaziland');
$countries["SE"] = array('value' => 46, 'name' => 'Sweden');
$countries["CH"] = array('value' => 41, 'name' => 'Switzerland');
$countries["SY"] = array('value' => 963, 'name' => 'Syria');
$countries["TW"] = array('value' => 886, 'name' => 'Taiwan');
$countries["TJ"] = array('value' => 992, 'name' => 'Tajikistan');
$countries["TH"] = array('value' => 66, 'name' => 'Thailand');
$countries["TG"] = array('value' => 228, 'name' => 'Togo');
$countries["TO"] = array('value' => 676, 'name' => 'Tonga');
$countries["TT"] = array('value' => 1868, 'name' => 'Trinidad &amp; Tobago');
$countries["TN"] = array('value' => 216, 'name' => 'Tunisia');
$countries["TR"] = array('value' => 90, 'name' => 'Turkey');
$countries["TM"] = array('value' => 993, 'name' => 'Turkmenistan');
$countries["TC"] = array('value' => 1649, 'name' => 'Turks & Caicos Islands');
$countries["TV"] = array('value' => 688, 'name' => 'Tuvalu');
$countries["UG"] = array('value' => 256, 'name' => 'Uganda');
$countries["UA"] = array('value' => 380, 'name' => 'Ukraine');
$countries["AE"] = array('value' => 971, 'name' => 'United Arab Emirates');
$countries["US"] = array('value' => 1, 'name' => 'USA');
$countries["GB"] = array('value' => 44, 'name' => 'UK');
$countries["UY"] = array('value' => 598, 'name' => 'Uruguay');
$countries["UZ"] = array('value' => 998, 'name' => 'Uzbekistan');
$countries["VU"] = array('value' => 678, 'name' => 'Vanuatu');
$countries["VA"] = array('value' => 379, 'name' => 'Vatican City');
$countries["VE"] = array('value' => 58, 'name' => 'Venezuela');
$countries["VN"] = array('value' => 84, 'name' => 'Vietnam');
$countries["VG"] = array('value' => 1, 'name' => 'Virgin Islands - British');
$countries["VI"] = array('value' => 1, 'name' => 'Virgin Islands - US');
$countries["WF"] = array('value' => 681, 'name' => 'Wallis &amp; Futuna');
$countries["YE"] = array('value' => 969, 'name' => 'Yemen');
$countries["YE"] = array('value' => 967, 'name' => 'Yemen');
$countries["ZM"] = array('value' => 260, 'name' => 'Zambia');
$countries["ZW"] = array('value' => 263, 'name' => 'Zimbabwe');

echo '<select id="country_select" name="country_number">';
echo '<option value="" ' . ($userCountryNumber == null ? 'selected' : '') . '>-- Select country --</option>';

foreach($countries as $countryCode => $country) {
    echo '<option data-countryCode="' . $countryCode . '" value="' . $country['value'] . '" ' . ($userCountryNumber == $country['value'] ? 'selected' : '') . '>' . $country['name'] . ' (+' . $country['value'] . ')</option>';
}
echo '</select>';
